name: diabetesapp
description: Building an application to monitor the diabetic on android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.6
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.3+1
  firebase_database: ^4.1.0
  connectivity: ^2.0.2
  http: ^0.12.2
  fluttertoast: ^7.1.1
  flutter_svg: ^0.19.1
  flutter_facebook_login: ^3.0.0
  pedometer: ^2.0.2
  percent_indicator: ^2.1.8
  jiffy: ^3.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  image_picker: ^0.6.7+12
  firebase_storage: ^5.0.1
  permission_handler: ^5.0.1+1
  charts_flutter: ^0.9.0
  flutter_local_notifications: ^1.4.4+1
  device_info: ^1.0.0
  rxdart: ^0.24.1
  path_provider: ^1.6.24
  timezone: ^0.5.9
  hive_generator: ^0.8.1
  build_runner: ^1.10.4
  table_calendar: ^2.3.0
  intl: ^0.16.1
  shared_preferences: ^0.5.12+2
  flutter_datetime_picker: ^1.4.0
  pdf: ^1.12.0
  advance_pdf_viewer: ^1.2.1+1
  flutter_full_pdf_viewer: ^1.0.6
  progress_dialog: ^1.2.4
  shake: ^0.1.0
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
#    - family: Brand-Bold
#      fonts:
#        - asset: fonts/bolt-semibold.ttf
#    - family: Brand-Regular
#      fonts:
#         - asset: fonts/bolt-regular.ttf
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/muli/Muli.ttf
#        - asset: assets/fonts/muli/Muli-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/muli/Muli-Light.ttf
#          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
